import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React from "react";

type WebpageLayoutProps = {
    isLoggedIn: boolean;
    pageTitle: string;
    children: React.ReactNode;
};

const WebpageLayout: NextPage<WebpageLayoutProps> = ({ pageTitle, children, isLoggedIn }) => {
    return (
        <div>
            <Head>
                <title>{pageTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon-logo.png" />
            </Head>
            <nav className="flex flex-row justify-center">
                <div className="flex flex-row lg:w-5/6  w-full p-1">
                    {/* navigation Muneem */}
                    <div className="flex flex-row flex-nowrap">
                        <div className="pt-2 pl-2">
                            <svg
                                className="p-1"
                                width="45"
                                height="45"
                                viewBox="0 0 300 300"
                                xmlns="http://www.w3.org/2000/svg"
                            >
                                <path
                                    className="fill-black dark:fill-white"
                                    fillRule="evenodd"
                                    clipRule="evenodd"
                                    d="M300 0L262.5 38.6974V38.8742L149.86 155.111L0 0.464892V0.506275V55.1913V299.509H6.25V61.6409L149.784 209.758L150.19 209.339L150.266 209.418L262.5 93.6007V300H300V54.9032V0.176818V0ZM150.025 223.646L253.125 117.254V117.312H253.204V299.865H246.954V178.349L150.266 278.123L150.025 277.874L149.784 278.123L51.875 177.088V299.865H14.375V138.391V98.0335V83.6644L150.025 223.646Z"
                                    fill="#FFFEFE"
                                />
                            </svg>
                        </div>
                        <h1 className="text-4xl self-end  m-0">uneem</h1>
                    </div>
                    <div className="flex-1 flex flex-col justify-end">
                        <ul className="flex flex-row gap-5 justify-center mb-1">
                            <li>
                                <Link href="/">
                                    <a>Home</a>
                                </Link>
                            </li>
                            <li>
                                <Link href="/">
                                    <a>About</a>
                                </Link>
                            </li>
                            <li>
                                <Link href="/">
                                    <a>Blog</a>
                                </Link>
                            </li>
                        </ul>
                    </div>
                    <div className="flex flex-row items-end gap-3 pr-3">
                        {!isLoggedIn ? (
                            <>
                                <p className="mb-1">
                                    <Link href="/auth/login">
                                        <a href="">Sign In</a>
                                    </Link>
                                </p>
                                <Link href="/auth/register">
                                    <button className="bg-slate-800 text-white p-1 pr-2 pl-2 rounded-md">
                                        Register
                                    </button>
                                </Link>
                            </>
                        ) : (
                            <Link href="/dashboard">
                                <button className="bg-slate-800 text-white p-1 pr-2 pl-2 rounded-md">
                                    Open Dashboard
                                </button>
                            </Link>
                        )}
                    </div>
                </div>
            </nav>
            {children}
        </div>
    );
};

export default WebpageLayout;
